### ISSUE TITLE
Sqlite3 on lustre

### ISSUE THREAD

**Issue by scemama** [TApplencourt/EMSL_Basis_Set_Exchange_Local#6]
Sqlite3 doesn't always work on lustre file systems :
```
Traceback (most recent call last):
  File "/store/cpq1738/scemama/quantum_package_static/EMSL_Basis//EMSL_api.py", line 91, in <module>
    l = e.get_basis(basis_name, elts,arguments["--with_l"])
  File "/store/cpq1738/scemama/quantum_package_static/EMSL_Basis/src/EMSL_utility.py", line 350, in get_basis
    cmd_ele=cmd_ele))
sqlite3.OperationalError: disk I/O error
```
Todo:
If error, then copy db to `/dev/shm/emsl.db` and then open `/dev/shm/emsl.db`

**Comment by TApplencourt** [comment]
#7 Solve
