### ISSUE TITLE
Failed "L" shell expansion

### ISSUE THREAD

**Issue by mattbernst** [TApplencourt/EMSL_Basis_Set_Exchange_Local#8]
Hi, I have forked your repository and I am currently trying to add support for additional basis set formats. I need test cases to cover the functionality that is already there for GAMESS-US. I can't get the "L" shell handling to work. Do you have an example that does work?

```
$ ./EMSL_api.py get_basis_data --basis=cc-pwCV5Z-RI --atom=Zn
Traceback (most recent call last):
  File "./EMSL_api.py", line 107, in <module>
    l = e.get_basis(basis_name, elts, arguments["--with_l"])
  File "/home/matt/EMSL_Basis_Set_Exchange_Local/src/EMSL_utility.py", line 635, in get_basis
    l_data = self.process_raw_data(l_data_raw, with_l)
  File "/home/matt/EMSL_Basis_Set_Exchange_Local/src/EMSL_utility.py", line 599, in process_raw_data
    tail_p = common + "{:>23.7f}".format(float(a[3]))
IndexError: list index out of range
```

Thanks,
Matt

**Comment by TApplencourt** [comment]
Hi,
Thanks for the bug report  @mattbernst! I have fix it in commit 284c697. 
The problem was L function with only one coefficient. You can now pull request for upgrade your fork.

`./EMSL_api.py get_basis_data --basis=cc-pwCV5Z-RI --atom=Zn`
```
ZINC
S   1
  1     47.115200000            1.0000000        
S   1
  1     27.991800000            1.0000000        
S   1
  1     16.796700000            1.0000000        
S   1
  1     10.029200000            1.0000000        
S   1
  1      6.6480300000           1.0000000        
S   1
  1      4.0045900000           1.0000000        
S   1
  1      2.5659400000           1.0000000        
S   1
  1      1.3908100000           1.0000000        
S   1
  1      0.76734900000          1.0000000        
S   1
  1      0.41301700000          1.0000000        
S   1
  1      0.21334500000          1.0000000    
...
```
If you have more question don't hesitate.
Hope the code will be clear enough. I can provide (aka write it) doc if you want,

Thomas
